export type ToolCatalogArea =
  | 'intelligence'
  | 'strategy'
  | 'actions'
  | 'tools'
  | 'reporting'
  | 'validation'
  | 'automation'
  | 'technical';

export type ToolCatalogStatus =
  | 'legacy'
  | 'migrated'
  | 'beta'
  | 'candidate'
  | 'planned'
  | 'unavailable';

export type ToolCatalogMaturity = 'idea' | 'prototype' | 'usable' | 'stable' | 'deprecated';
export type ToolCatalogPriority = 'P1' | 'P2' | 'P3';
export type ToolCatalogLevel = 'low' | 'medium' | 'high';
export type ToolCatalogOutput =
  | 'insight'
  | 'task'
  | 'report'
  | 'snapshot'
  | 'recommendation'
  | 'export';

export interface SharedToolCatalogItem {
  id: string;
  name: string;
  description: string;
  category: string;
  area: ToolCatalogArea;
  status: ToolCatalogStatus;
  maturity: ToolCatalogMaturity;
  priority: ToolCatalogPriority;
  seoImpact: ToolCatalogLevel;
  technicalDifficulty: ToolCatalogLevel;
  risk: ToolCatalogLevel;
  dependencies: string[];
  reusableCode: ToolCatalogLevel;
  ownerArea: string;
  recommendedRoute: string;
  canRunInQueue: boolean;
  supportsDryRun: boolean;
  requiresHumanReview: boolean;
  isReadOnlySafe: boolean;
  outputs: ToolCatalogOutput[];
  notes: string;
}

export const sharedToolsCatalog: SharedToolCatalogItem[] = [
  {
    id: 'gsc-impact-analyzer',
    name: 'GSC Impact',
    description: 'Análisis de impacto y señales Search Console ya integrado en la SPA.',
    category: 'Analítica SEO',
    area: 'intelligence',
    status: 'migrated',
    maturity: 'usable',
    priority: 'P1',
    seoImpact: 'high',
    technicalDifficulty: 'medium',
    risk: 'medium',
    dependencies: ['GSC', 'propiedad verificada', 'periodos comparables'],
    reusableCode: 'high',
    ownerArea: 'Intelligence',
    recommendedRoute: '/app/gsc-impact',
    canRunInQueue: false,
    supportsDryRun: false,
    requiresHumanReview: true,
    isReadOnlySafe: true,
    outputs: ['insight', 'snapshot', 'recommendation'],
    notes:
      'Fuente principal para validar evidencias de rendimiento antes de priorizar por caída o crecimiento.',
  },
  {
    id: 'seo-checklist-audit',
    name: 'Checklist SEO',
    description:
      'Auditoría técnica/editorial existente para convertir hallazgos en señales accionables.',
    category: 'Auditoría',
    area: 'technical',
    status: 'migrated',
    maturity: 'usable',
    priority: 'P1',
    seoImpact: 'high',
    technicalDifficulty: 'medium',
    risk: 'low',
    dependencies: ['cliente activo', 'URLs o páginas auditables'],
    reusableCode: 'high',
    ownerArea: 'Intelligence',
    recommendedRoute: '/app/checklist',
    canRunInQueue: false,
    supportsDryRun: false,
    requiresHumanReview: true,
    isReadOnlySafe: true,
    outputs: ['insight', 'task', 'recommendation'],
    notes: 'Debe seguir siendo el punto de auditoría, no duplicarse dentro de Metodología.',
  },
  {
    id: 'tools-hub-launcher',
    name: 'Tools Hub Launcher',
    description: 'Panel existente de apps, launchers y runtime operativo.',
    category: 'Gobierno de herramientas',
    area: 'tools',
    status: 'beta',
    maturity: 'usable',
    priority: 'P1',
    seoImpact: 'medium',
    technicalDifficulty: 'medium',
    risk: 'medium',
    dependencies: ['catálogo backend', 'launcher catalog', 'runtime local'],
    reusableCode: 'high',
    ownerArea: 'Tools Hub',
    recommendedRoute: '/app/tools-hub',
    canRunInQueue: false,
    supportsDryRun: false,
    requiresHumanReview: true,
    isReadOnlySafe: true,
    outputs: ['recommendation'],
    notes:
      'La ejecución de herramientas permanece en Tools Hub; Metodología solo consume gobierno read-only.',
  },
  {
    id: 'cannibalization-detector',
    name: 'Detector de canibalización',
    description:
      'Detecta URLs que compiten por las mismas consultas y propone consolidación o diferenciación.',
    category: 'Diagnóstico de contenidos',
    area: 'intelligence',
    status: 'candidate',
    maturity: 'prototype',
    priority: 'P1',
    seoImpact: 'high',
    technicalDifficulty: 'medium',
    risk: 'medium',
    dependencies: ['GSC queries/pages', 'clusters', 'reglas de intención'],
    reusableCode: 'high',
    ownerArea: 'Intelligence',
    recommendedRoute: '/app/gsc-impact',
    canRunInQueue: true,
    supportsDryRun: true,
    requiresHumanReview: true,
    isReadOnlySafe: true,
    outputs: ['insight', 'recommendation'],
    notes: 'Buen candidato para dry-run antes de generar tareas.',
  },
  {
    id: 'internal-linking-recommender',
    name: 'Recomendador de enlazado interno',
    description:
      'Propone enlaces internos seguros a partir de arquitectura, clusters y oportunidades.',
    category: 'Arquitectura',
    area: 'automation',
    status: 'planned',
    maturity: 'idea',
    priority: 'P1',
    seoImpact: 'high',
    technicalDifficulty: 'high',
    risk: 'medium',
    dependencies: ['crawler', 'link graph', 'clusters', 'prioridad de URLs'],
    reusableCode: 'high',
    ownerArea: 'Acciones',
    recommendedRoute: '/app/kanban',
    canRunInQueue: true,
    supportsDryRun: false,
    requiresHumanReview: true,
    isReadOnlySafe: false,
    outputs: ['recommendation', 'task'],
    notes: 'No debe entrar en Cola SEO sin dry-run y revisión humana.',
  },
  {
    id: 'indexation-monitor',
    name: 'Monitor de indexación',
    description: 'Monitoriza URLs sin indexar, cambios de cobertura y prioridades de revisión.',
    category: 'Indexación',
    area: 'intelligence',
    status: 'planned',
    maturity: 'idea',
    priority: 'P1',
    seoImpact: 'high',
    technicalDifficulty: 'medium',
    risk: 'high',
    dependencies: ['GSC inspection', 'sitemap', 'crawler'],
    reusableCode: 'high',
    ownerArea: 'Intelligence',
    recommendedRoute: '/app/gsc-impact',
    canRunInQueue: true,
    supportsDryRun: false,
    requiresHumanReview: true,
    isReadOnlySafe: true,
    outputs: ['insight', 'snapshot', 'recommendation'],
    notes: 'Requiere diseño cuidadoso por cuotas y APIs externas.',
  },
  {
    id: 'serp-kw-clusterizer',
    name: 'Clusterizador SERP/KW',
    description: 'Agrupa keywords por similitud SERP e intención para estrategia de contenidos.',
    category: 'Clusterización',
    area: 'intelligence',
    status: 'candidate',
    maturity: 'prototype',
    priority: 'P2',
    seoImpact: 'high',
    technicalDifficulty: 'high',
    risk: 'medium',
    dependencies: ['SERP provider', 'keywords', 'similaridad semántica'],
    reusableCode: 'medium',
    ownerArea: 'Intelligence',
    recommendedRoute: '/app/checklist',
    canRunInQueue: true,
    supportsDryRun: true,
    requiresHumanReview: true,
    isReadOnlySafe: true,
    outputs: ['insight', 'recommendation', 'export'],
    notes: 'Encaja como herramienta read-only antes de proponer briefs o enlaces.',
  },
  {
    id: 'ai-brief-generator',
    name: 'Generador de briefs IA',
    description: 'Genera briefs revisables a partir de oportunidades, gaps y criterios del método.',
    category: 'Contenido IA',
    area: 'strategy',
    status: 'candidate',
    maturity: 'prototype',
    priority: 'P1',
    seoImpact: 'high',
    technicalDifficulty: 'medium',
    risk: 'medium',
    dependencies: ['LLM', 'SERP/KW', 'plantillas editoriales'],
    reusableCode: 'high',
    ownerArea: 'Estrategia',
    recommendedRoute: '/app/ai-roadmap',
    canRunInQueue: true,
    supportsDryRun: true,
    requiresHumanReview: true,
    isReadOnlySafe: false,
    outputs: ['recommendation', 'export'],
    notes: 'Debe producir borradores revisables, nunca publicación automática.',
  },
  {
    id: 'schema-validator',
    name: 'Validador de schema',
    description: 'Valida marcado estructurado y genera recomendaciones de corrección.',
    category: 'SEO técnico',
    area: 'technical',
    status: 'candidate',
    maturity: 'prototype',
    priority: 'P1',
    seoImpact: 'medium',
    technicalDifficulty: 'medium',
    risk: 'low',
    dependencies: ['HTML fetch', 'schema parser', 'reglas de validación'],
    reusableCode: 'high',
    ownerArea: 'Tools Hub',
    recommendedRoute: '/app/tools-hub',
    canRunInQueue: true,
    supportsDryRun: true,
    requiresHumanReview: false,
    isReadOnlySafe: true,
    outputs: ['insight', 'recommendation'],
    notes: 'Buen primer candidato técnico para catálogo read-only.',
  },
  {
    id: 'url-kw-meta-matrix',
    name: 'Matriz URL + KW + Title + Meta',
    description:
      'Cruza URLs, keywords y metadatos para detectar gaps, duplicados y oportunidades de CTR.',
    category: 'Inventario SEO',
    area: 'intelligence',
    status: 'candidate',
    maturity: 'prototype',
    priority: 'P1',
    seoImpact: 'high',
    technicalDifficulty: 'medium',
    risk: 'low',
    dependencies: ['crawler', 'GSC', 'checklist'],
    reusableCode: 'high',
    ownerArea: 'Intelligence',
    recommendedRoute: '/app/checklist',
    canRunInQueue: true,
    supportsDryRun: true,
    requiresHumanReview: false,
    isReadOnlySafe: true,
    outputs: ['insight', 'export', 'recommendation'],
    notes: 'Apto para análisis y exportación sin cambios operativos.',
  },
  {
    id: 'report-generator',
    name: 'Generador de informes',
    description: 'Compone entregables ejecutivos y técnicos con evidencias y before/after.',
    category: 'Reporting',
    area: 'reporting',
    status: 'planned',
    maturity: 'idea',
    priority: 'P2',
    seoImpact: 'high',
    technicalDifficulty: 'medium',
    risk: 'medium',
    dependencies: ['snapshots', 'tareas', 'GSC', 'exportaciones'],
    reusableCode: 'medium',
    ownerArea: 'Reporting',
    recommendedRoute: '/app/completed-tasks',
    canRunInQueue: true,
    supportsDryRun: true,
    requiresHumanReview: true,
    isReadOnlySafe: false,
    outputs: ['report', 'export'],
    notes: 'Debe esperar a Fase 7 para exportaciones finales.',
  },
  {
    id: 'link-building-crm',
    name: 'CRM de link building',
    description: 'Gestiona oportunidades, contactos y seguimiento de campañas de autoridad.',
    category: 'Autoridad',
    area: 'actions',
    status: 'planned',
    maturity: 'idea',
    priority: 'P3',
    seoImpact: 'medium',
    technicalDifficulty: 'high',
    risk: 'high',
    dependencies: ['prospectos', 'contactos', 'estados', 'privacidad'],
    reusableCode: 'medium',
    ownerArea: 'Acciones',
    recommendedRoute: '/app/kanban',
    canRunInQueue: false,
    supportsDryRun: false,
    requiresHumanReview: true,
    isReadOnlySafe: false,
    outputs: ['task', 'report'],
    notes: 'Requiere política de privacidad y permisos antes de integrarse.',
  },
  {
    id: 'content-gap-analysis',
    name: 'Análisis de gaps de contenido',
    description:
      'Identifica temas, formatos y URLs faltantes frente a competidores o intención de búsqueda.',
    category: 'Contenido',
    area: 'intelligence',
    status: 'candidate',
    maturity: 'prototype',
    priority: 'P1',
    seoImpact: 'high',
    technicalDifficulty: 'medium',
    risk: 'medium',
    dependencies: ['competidores', 'SERP', 'keywords', 'clusters'],
    reusableCode: 'high',
    ownerArea: 'Intelligence',
    recommendedRoute: '/app/checklist',
    canRunInQueue: true,
    supportsDryRun: true,
    requiresHumanReview: true,
    isReadOnlySafe: true,
    outputs: ['insight', 'recommendation'],
    notes: 'Prioritario para estrategia de contenidos si hay clusters y GSC.',
  },
  {
    id: 'geo-aeo-llms',
    name: 'GEO/AEO/LLMs',
    description:
      'Evalúa visibilidad en respuestas IA, entidades, menciones y señales de autoridad.',
    category: 'IA Visibility',
    area: 'intelligence',
    status: 'beta',
    maturity: 'prototype',
    priority: 'P2',
    seoImpact: 'high',
    technicalDifficulty: 'high',
    risk: 'high',
    dependencies: ['prompts', 'LLM providers', 'competidores', 'histórico'],
    reusableCode: 'high',
    ownerArea: 'Intelligence',
    recommendedRoute: '/app/ai-roadmap',
    canRunInQueue: true,
    supportsDryRun: true,
    requiresHumanReview: true,
    isReadOnlySafe: true,
    outputs: ['insight', 'recommendation', 'report'],
    notes: 'Debe permanecer auditado por coste, sesgo y trazabilidad de prompts.',
  },
  {
    id: 'before-after-control',
    name: 'Control before/after',
    description: 'Relaciona acciones completadas con evolución de métricas y evidencia de impacto.',
    category: 'Validación',
    area: 'validation',
    status: 'migrated',
    maturity: 'usable',
    priority: 'P1',
    seoImpact: 'high',
    technicalDifficulty: 'medium',
    risk: 'low',
    dependencies: ['snapshots', 'tareas realizadas', 'GSC'],
    reusableCode: 'high',
    ownerArea: 'Acciones',
    recommendedRoute: '/app/completed-tasks',
    canRunInQueue: false,
    supportsDryRun: false,
    requiresHumanReview: true,
    isReadOnlySafe: true,
    outputs: ['snapshot', 'insight', 'report'],
    notes: 'Conecta tareas realizadas con validación sin ejecutar nuevas acciones.',
  },
  {
    id: 'impact-effort-prioritizer',
    name: 'Priorizador impacto/esfuerzo',
    description:
      'Ordena iniciativas por impacto, esfuerzo, urgencia, confianza y valor para negocio.',
    category: 'Priorización',
    area: 'strategy',
    status: 'beta',
    maturity: 'usable',
    priority: 'P1',
    seoImpact: 'high',
    technicalDifficulty: 'medium',
    risk: 'medium',
    dependencies: ['insights', 'tareas', 'estimación de esfuerzo', 'valor de negocio'],
    reusableCode: 'high',
    ownerArea: 'Estrategia',
    recommendedRoute: '/app/metodologia#priorizacion',
    canRunInQueue: false,
    supportsDryRun: false,
    requiresHumanReview: false,
    isReadOnlySafe: true,
    outputs: ['recommendation'],
    notes: 'Implementado visualmente como scoring read-only dentro de Metodología.',
  },
];
