import { Listing } from "@/lib/types";

export const MOCK_LISTINGS: Listing[] = [
  {
    sourceId: "dfs_001",
    businessName: "Clínica Dental Centro Sonrisa",
    primaryCategory: "Clinica dental",
    secondaryCategories: ["Ortodoncia", "Implantes dentales"],
    address: "Calle Mayor 10",
    phone: "+34 910000001",
    website: "https://centrosonrisa.example",
    rating: 4.8,
    reviewCount: 312,
    workHours: "L-V 09:00-20:00",
    attributes: ["Urgencias", "Financiación", "Accesible"],
    lat: 40.4168,
    lng: -3.7038,
    source: "dataforseo_v3"
  },
  {
    sourceId: "dfs_002",
    businessName: "Dental Norte 24h",
    primaryCategory: "Dentista",
    secondaryCategories: ["Urgencias dentales"],
    address: "Avenida Norte 22",
    phone: "+34 910000002",
    website: "https://dentalnorte.example",
    rating: 4.5,
    reviewCount: 180,
    workHours: "24h",
    attributes: ["Urgencias", "Parking"],
    lat: 40.429,
    lng: -3.695,
    source: "dataforseo_v3"
  },
  {
    sourceId: "dfs_003",
    businessName: "Centro Estética Bella Piel",
    primaryCategory: "Centro de estética",
    secondaryCategories: ["Depilación láser"],
    address: "Calle Sol 44",
    phone: "+34 910000003",
    website: "https://bellapiel.example",
    rating: 4.7,
    reviewCount: 210,
    workHours: "L-S 10:00-21:00",
    attributes: ["Cita previa", "Tarjeta"],
    lat: 40.412,
    lng: -3.71,
    source: "dataforseo_v3"
  },
  {
    sourceId: "pl_001",
    businessName: "Clínica Dental Barrio Salamanca",
    primaryCategory: "Clinica dental",
    secondaryCategories: ["Odontopediatría", "Implantes"],
    address: "Calle Goya 88",
    phone: "+34 910000004",
    website: "https://dentalbarrio.example",
    rating: 4.2,
    reviewCount: 96,
    workHours: "L-V 10:00-19:00",
    attributes: ["Accesible"],
    lat: 40.425,
    lng: -3.686,
    source: "google_places_new"
  },
  {
    sourceId: "pl_002",
    businessName: "Laboratorio Radiológico Centro",
    primaryCategory: "Laboratorio de radiología",
    secondaryCategories: ["Diagnóstico"],
    address: "Gran Vía 55",
    phone: "+34 910000005",
    website: "https://radiocentro.example",
    rating: 3.9,
    reviewCount: 45,
    workHours: "L-V 08:00-18:00",
    attributes: ["Sin cita"],
    lat: 40.42,
    lng: -3.705,
    source: "google_places_new"
  }
];
